import type { Metadata } from "next";
import { ToastContainer } from 'react-toastify';
import { Inter } from "next/font/google";
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';
import Providers from "./components/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "X. Its whats happening / X",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {children}
          <ToastContainer 
            position="bottom-left"
            theme="dark"
            autoClose={3000}
          />
        </Providers>
      </body>
    </html>
  );
}
